### ISSUE TITLE
Can't scan video library "via extractor EMBEDDED. Message: No such device"

### ISSUE THREAD

**Issue by jjslegacy** [linuxserver/docker-serviio#12]
I just realized my library hasn't been updated in a while.  Looking at the serviio Log all entries get:

2016-11-21 09:49:38,543 WARN  [MetadataExtractionCoordinator] Cannot read metadata of file /movies/KIDS_BLURAY/Ice Age, Collision Course (2016)/Ice Age, Collision Course (2016).mkv via extractor EMBEDDED. Message: No such device

This is running on Unraid 6.3.0 RC4

**Comment by jjslegacy** [comment]
Docker LOG:
-------------------------------------
_ _ _
| |___| (_) ___
| / __| | |/ _ \
| \__ \ | | (_) |
|_|___/ |_|\___/
|_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by CHBMB** [comment]
Can't reproduce this despite testing.

**Comment by maciekb** [comment]
I've had the same issue. It is caused by "Tunable (enable Direct IO):" setting set to ON under Settings->Global Share Settings.

**Comment by CHBMB** [comment]
@maciekb Thanks
