### ISSUE TITLE
Allow to pass java params via env variables

### ISSUE THREAD

**Issue by serhiicherepanov** [linuxserver/docker-serviio#15]
Currently not possible to change java args, because it's hardcoded in the daemon script: "-Xmx512M -Xms20M -XX:+UseG1GC -XX:GCTimeRatio=1 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 "

**Comment by sparklyballs** [comment]
you're welcome to PR against this repository.
