### ISSUE TITLE
Config mount point

### ISSUE THREAD

**Issue by sprat** [linuxserver/docker-serviio#2]
I am using the serviio image (https://github.com/linuxserver/docker-serviio) and I've a problem. It's advertised in the documentation that we should mount a host directory into /config to avoid storing it into the container, but if you mount say "/home" or "/config", the ownership of this directory is changed to the serviio user and group which is very annoying. Maybe there's a way to avoid that?

The problem lies in the base image: https://github.com/linuxserver/docker-baseimage/blob/master/10_add_user_abc.sh#L31

For now, I've mounted "/home/serviio" with "/config/serviio", which seems to work, but I don't understand why (I'm new to docker). Maybe the image should only expose /config/serviio as mount point?

**Comment by lonix** [comment]
I am a little blurred on upon When you are talking about your host vs your container.

The container should use the permissions of whatever id you set for PUID PGID (enviromental variables, see the readme).

**Comment by sprat** [comment]
Sorry, I was not clear.

I've built my docker container with: -v /home:/config. But when I launch the container, the /home directory of my host change ownership => it gets the user/group defined by PUID/GUID

So I've rebuilt my docker container with : -v /home/serviio:/config/serviio, and no problem anymore

**Comment by lonix** [comment]
It should be used with e.g. -v /home/<your username>/serviio:/config

**Comment by lonix** [comment]
Disreggard my last comment.
