### ISSUE TITLE
Postforwarding issues

### ISSUE THREAD

**Issue by Homer-Sim** [linuxserver/docker-serviio#21]
Hello, I have a question about Serviio container. I
t is running (seen by renderers) in case I am switching from automatic to host ip address. But if I do so I see in my router not the given server name srv-docker. I see instead serviio-srv-docker on the same IP Address. Basically it is no issue but after that my port forwarding is not working. I cannot select this ip or server name for portforwarding??

This is ma docker run command:
docker run -it -d --name=serviio \
  -p 23423:23423 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /docker/config/serviio:/config \
  -v /docker/data:/media \
  -v /tmp/serviio:/transcode \
  --restart=always \
  -e PUID=33 -e PGID=33 \
  --net=host lsiocommunity/serviio

**Comment by sparklyballs** [comment]
you can't specify a port and run in host mode.
